### ISSUE TITLE
Update Chrome driver to support browser v74

### ISSUE THREAD

**Issue by markdwhite** [laravel/dusk#641]
- Dusk Version: 5.0.3
- Laravel Version: 5.8.14
- PHP Version: 7.2.17
- Database Driver & Version: mySQL 5.7.25

### Description:
Chrome 74 is now available. The current driver has not been updated for 4 months and supports Chrome 70-73 only.

(Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-47-generic x86_64)
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73

However...chromedriver 74.X does not explicitly support older versions:
https://chromedriver.storage.googleapis.com/74.0.3729.6/notes.txt

Compared to 2.45.X which clearly supports a range of versions 70-73 (and 2.46) but not 74:
https://chromedriver.storage.googleapis.com/2.45/notes.txt
https://chromedriver.storage.googleapis.com/2.46/notes.txt

Does this mean we have to wait for a version that has a more encompassing support so we don't lose backwards compatibility? So we're either pinning Chrome to 73 or using a standalone driver rather than the packaged driver?

Cheers.

**Comment by Kumidan** [comment]
I'm facing the exact same issue.

**Comment by ahtinurme** [comment]
Same here.

**Comment by tentus** [comment]
Same.

**Comment by rmeira** [comment]
same isue

**Comment by staudenmeir** [comment]
In the meantime, you can use my updater package: https://github.com/staudenmeir/dusk-updater

**Comment by markdwhite** [comment]
> In the meantime, you can use my updater package: https://github.com/staudenmeir/dusk-updater

The reply is appreciated and hopefully it will help some as copying the 74.X chromedriver executable into laravel/dusk/bin will work for local dev. However it doesn't work for CI and an update to the package will be needed at some point. Which may well not happened until a 2.47 chromedriver is released that covers a few versions of Chrome.

**Comment by staudenmeir** [comment]
The ChromeDriver release strategy has changed and it looks like there will be no more releases that support multiple versions of Chrome: http://chromedriver.chromium.org/downloads/version-selection

Why doesn't the updater work for CI?

**Comment by markdwhite** [comment]
> The ChromeDriver release strategy has changed and it looks like there will be no more releases that support multiple versions of Chrome

That does look like it's the case. I'd looked at that and hoped/expected that something like 2.47 might support a range of browsers when it's released, but it does look like new drivers have only been built to support specific versions and maybe a 2.47 is not in the works. 

Which would suggest that this package will become awkward to use in it's current state: I don't mind using the current version of a browser (though it's caught me out this time, and I think it caught me out before too - maybe I should learn from this :) but having to use the current version because Dusk can only support one version at a time in the future might not be ideal for everyone. 

**Because of that, there may be a need to provide a number of chromedrivers in the package with an option to use any of them.**

It looks like the simplest solution for now is to make the correct version of the chromedriver available somewhere in your code repo and adding static::useChromedriver($path) to DuskTestCase::prepare().

> Why doesn't the updater work for CI?

Fair enough - it will work by running the command on the CI server after the Dusk package is updated. Which is either a manual step or a change to the build file to do this as part of the build process. My first comment reflected that I prefer not to make changes to the contents of /vendor as these cannot be reflected in the project's repo where there are alternatives that can be contained within the project code. But I can see that it would work. 

However, I'll just go with manually setting which chromedriver to use until we get a solution from the maintainers of the repo. 'Cause using work-arounds to make up for issues in packages generally suck and get piddly to maintain. And others with the issue can chose which solution works best for them as this is all libre here :)

**So some official comment on what's likely to happen here would be really appreciated**

**Comment by markdwhite** [comment]
I just closed this by mistake...

**Comment by flexnst** [comment]
same issue.

**Comment by driesvints** [comment]
Please use the package from staudenmeier until we update the driver.

**Comment by peterfox** [comment]
Ran into this problem this morning. I can't see many options other than no longer storing the chrome driver in the package and adding a command to check for the version of chrome, downloading the right version before running dusk for the first time and keeping it under the vendor folder outside of source control. At 5mb it's not too bad to keep it in the package but if there will be a new driver for each major chrome release it might become a bit excessive to have multiple copies in the repo.

**Comment by krb19xx** [comment]
Same problem...

**Comment by bobo52310** [comment]
Same issue.

**Comment by driesvints** [comment]
The new `dusk:chrome-driver` command has now been released.

**Comment by Tarasovych** [comment]
I have tried
```
php artisan dusk:chrome-driver 73
```
and
```
php artisan dusk
```
Anyway I got

> Facebook\WebDriver\Exception\UnknownServerException: unknown error: cannot find Chrome binary
>   (Driver info: chromedriver=72.0.3626.69 (3c16f8a135abc0d4da2dff33804db79b849a7c38),platform=Linux 4.15.0-47-generic x86_64)

What should I do more?

**Comment by staudenmeir** [comment]
@Tarasovych Please try terminating all running ChromeDriver processes.

**Comment by Tarasovych** [comment]
@staudenmeir that's strange, but:
```
ps -aux | grep chrome
```
returns a new one process each time, so after I found its PID and go
```
kill <PID>
```
, it just outputs

> No such process

I'm working in Homestead, tried
```
php artisan reload --provision
```
and relogin into VM, didn't helped

**Comment by staudenmeir** [comment]
What's the result of `chromium-browser --version`?

**Comment by Tarasovych** [comment]
@staudenmeir thanks, found my problem after your comment. Solved now.

**Comment by tatebosler** [comment]
Still getting this error, even after running `dusk:chrome-driver` - I'm on Mac 10.14.4.

```
$ php artisan dusk:chrome-driver 73
ChromeDriver binary successfully installed for version 73.0.3683.68.

$ ./vendor/laravel/dusk/bin/chromedriver-mac --version
ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72)

$ php artisan dusk
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.4 x86_64)
```

**Comment by driesvints** [comment]
@tatebosler where are you running the chrome driver and dusk command? Locally or on homestead or something else?

**Comment by driesvints** [comment]
Also: does it works when you run `php artisan dusk:chrome-driver 73 --all`?

**Comment by tatebosler** [comment]
Adding `--all` doesn't help; I'm running locally (not in Homestead).

**Comment by driesvints** [comment]
@tatebosler what's the version of your actual Chrome browser?

**Comment by staudenmeir** [comment]
What exact version of Chrome 73 are you using?

**Comment by driesvints** [comment]
Btw, I just realised that the issue might just be what it says? `Chrome version must be between 70 and 73`. `73` isn't in between that. 71 and 72 are however.

**Comment by tatebosler** [comment]
@driesvints 74. Problem solved, I ran `php artisan dusk:chrome-driver` without any arguments to update the driver to match the browser version, and tests are running smoothly now.

**Comment by Thijmen** [comment]
Problem is unfortunately for me not solved yet. @tatebosler Which Chrome version are you running?

**Comment by tatebosler** [comment]
@Thijmen Chrome (browser) version is `74.0.3729.131`, driver version that is working is `ChromeDriver 74.0.3729.6` (achieved by running `php artisan dusk:chrome-driver` without any additional arguments).

**Comment by Thijmen** [comment]
@tatebosler 
Chrome (browser) version here `74.0.3729.131`. 
ChromeDriver is `74.0.3729.6` archieved running `dusk:chrome-driver`.

No luck here. 
Running laravel 5.7.28 and laravel/dusk v5.1.0

**Comment by lnpbk** [comment]
@driesvints I just looked at this, and you're correct. `dusk:chrome-driver 72` installs `72.0.3626.69` and works for me

**Comment by tatebosler** [comment]
@Thijmen Are you getting the "session not created: Chrome version must be between 70 and 73" error when you run Dusk?

If so, run `./vendor/laravel/dusk/bin/chromedriver-mac --version` (if you're not on Mac, swap out `chromedriver-mac` for your OS) and compare that to the error message - there should be a diagnostic line like "Driver info: chromedriver=73.0.3683.68".

**Comment by peterfox** [comment]
I think some of the problems with this might be when you check the version of chrome in an already running instance but chrome has already updated itself. E.g. originally I looked at an already open chrome window and it told me I was using 73 but it'd already upgrade it to 74 so Dusk was opening new instances on this version. Didn't have 74 until I closed all browser windows. The best way to check the version and be sure is via command line or closing all windows and reopening them.

**Comment by Thijmen** [comment]
@tatebosler 
When I run ` ./vendor/laravel/dusk/bin/chromedriver-mac --version` it returns `ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29})`.

I also tried to reboot my Mac to make sure that there are no other processes for Chrome. What I can see, is that it keeps spawning Chrome Helper-processes.

Why am I having issues while you are not? It seems that we are running the same versions. What is causing my problem or how can I debug my case so we can work to a solution together?

**Comment by staudenmeir** [comment]
@Thijmen What error message do you get?

**Comment by driesvints** [comment]
@Thijmen since at the moment it's just you who is still experiencing this let's first try to figure out why that is.

**Comment by Thijmen** [comment]
@staudenmeir None. That's the most annoying. 

``
~ php artisan dusk --filter test_we_test_a_test
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
``
It just stops the test after like 20 seconds. No error, nothing. :(

**Comment by staudenmeir** [comment]
@Thijmen Has Dusk worked before?

**Comment by Thijmen** [comment]
@staudenmeir Yes, it perfectly did! Just after the last Chrome update, things started... not to work.

**Comment by staudenmeir** [comment]
@Thijmen Can you reproduce this on a fresh installation of Laravel?

**Comment by Thijmen** [comment]
@staudenmeir I see. There was something wrong with the testsuite of me, stupid. It is working now!

**Comment by SagarNaliyapara** [comment]
@staudenmeir I was able to fix using your package: https://github.com/staudenmeir/dusk-updater but again it creates issue,

### Previous Error
```
Facebook\WebDriver\Exception\SessionNotCreatedException : session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.13.2 x86_64)
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:154
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
 /Users/levaral/code/fixd-web/tests/DuskTestCase.php:58
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:192
 /Users/levaral/code/fixd-web/vendor/laravel/framework/src/Illuminate/Support/helpers.php:815
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:193
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:93
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:64
 /Users/levaral/code/fixd-web/tests/Browser/Tests/ScheduleDuskTest.php:109
```

Got fixed using your package:

### Current error
```
Facebook\WebDriver\Exception\SessionNotCreatedException : session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}),platform=Mac OS X 10.13.2 x86_64)
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:154
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
 /Users/levaral/code/fixd-web/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
 /Users/levaral/code/fixd-web/tests/DuskTestCase.php:58
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:192
 /Users/levaral/code/fixd-web/vendor/laravel/framework/src/Illuminate/Support/helpers.php:816
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:193
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:93
 /Users/levaral/code/fixd-web/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:64
 /Users/levaral/code/fixd-web/tests/Browser/Tests/SuppliersDuskTest.php:77
```

**Comment by staudenmeir** [comment]
@SagarNaliyapara What version of Chrome and what version of the package are you using? What command(s) are you running to update the ChromeDriver?

**Comment by bayubimantarar** [comment]
Working using [https://github.com/staudenmeir/dusk-updater](https://github.com/staudenmeir/dusk-updater). If using travis.yml add `php artisan dusk:update 74` on script before `php artisan dusk`

**Comment by SagarNaliyapara** [comment]
@staudenmeir My current chrome version is - 74.0.3729.131,

@bayubimantarar Thanks I got it fixed by running - ```php artisan dusk:update 74```

**Comment by bilfeldt** [comment]
I am using:

- PHP (v7.2.9)
- Laravel (v5.8.4)
- PHPUnit (v8.0.4)
- laravel/dusk (v5.1.0)

If I completely remove the folder `vendor/laravel/dusk` and run `composer install` then it installs `chromedriver=2.45.615279`

When running my tests I get the error that the 

```bash
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.

EEEEEEEEEEEEIEEEEEEEEEEEEEEEEEEEEEEIEEEEEEEIEIIEIEEEEIEEEEEEEEEEI 65 / 89 ( 73%)
IIIIEEEEEIEEEEEEEEEEEEEE                                          89 / 89 (100%)

Time: 9.4 minutes, Memory: 32.00 MB

There were 76 errors:

1) Tests\Browser\GuestDashboardTest::testSeeGuestDashboard
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73
(Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1031-aws x86_64)
```

I am able to update the chrome driver to version 72 (which is between 70 and 73 as stated in the error) using:
```
$ php artisan dusk:chrome-driver 72
ChromeDriver binary successfully installed for version 72.0.3626.69.

$ ./vendor/laravel/dusk/bin/chromedriver-mac --version
ChromeDriver 72.0.3626.69 (3c16f8a135abc0d4da2dff33804db79b849a7c38)
```
I am also able to update to the latest version which is 74 simply using:
```
$ php artisan dusk:chrome-driver
ChromeDriver binary successfully installed for version 74.0.3729.6.

$ ./vendor/laravel/dusk/bin/chromedriver-mac --version
ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29})
```

But I don't completely understand why the latest ChromeDriver version is not automatically installed when installing `laravel/dusk` - can anyone help me understand? Thanks.

**Comment by staudenmeir** [comment]
The ChromeDriver gets updated when you run `php artisan dusk:install`.

**Comment by michielgerritsen** [comment]
Please note that if you run `php artisan dusk:chrome-driver` you might need to update Chrome itself too, otherwise you might end up with this kind of errors although you have the correctly installed version of ChromeDriver:
```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}),platform=Mac OS X 10.14.5 x86_64)
```

**Comment by staudenmeir** [comment]
@andyscraven Your Homestead machine might also have Chromium installed.

Please try `chromium-browser --version`.

**Comment by andyscraven** [comment]
@staudenmeir Thanks for replying.

chromium-browser --version
Chromium 68.0.3440.106 Built on Ubuntu , running on Ubuntu 18.04

**Comment by staudenmeir** [comment]
With both Chrome and Chromium installed, Chromium takes precedence.

You can update Chromium with `sudo apt-get install --only-upgrade chromium-browser`.

**Comment by andyscraven** [comment]
from within homestead I assume?

**Comment by staudenmeir** [comment]
Yes.

**Comment by andyscraven** [comment]
I did that and got:

sudo apt-get install --only-upgrade chromium-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-browser is already the newest version (68.0.3440.106-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


I then ran and got:

php artisan dusk
PHPUnit 7.4.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.77 seconds, Memory: 16.00MB

There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.15.0-32-generic x86_64)

**Comment by staudenmeir** [comment]
Please run `sudo apt-get update` first.

**Comment by andyscraven** [comment]
So I did the following:

sudo apt-get update
Took a few seconds but succeeded.

Then:

sudo apt-get install --only-upgrade chromium-browser

but I think it installed version 74.

Setting up chromium-browser (74.0.3729.169-0ubuntu0.18.04.1) ...
Setting up chromium-browser-l10n (74.0.3729.169-0ubuntu0.18.04.1) ...

if I am right I need version 75, right?

so when I ran dusk I got the same error as before.

**Comment by staudenmeir** [comment]
Apparently, the Chromium repository doesn't offer the latest version.

You can try removing Chromium: `sudo apt-get purge chromium-browser`

**Comment by andyscraven** [comment]
And then run:

sudo apt-get install --only-upgrade chromium-browser

again?

**Comment by staudenmeir** [comment]
No, then Dusk should use Chrome and run successfully.

**Comment by staudenmeir** [comment]
How did you install Google Chrome in Homestead?

**Comment by andyscraven** [comment]
I installed dusk and it didn't work so first I installed your library that was a fix a while ago and I still had issues with that.  Hence asking.

composer require --dev laravel/dusk
php artisan dusk:install
php artisan dusk
composer require --dev staudenmeir/dusk-updater

and then the instructions you gave me.

**Comment by staudenmeir** [comment]
> Google Chrome is up to date
> Version 75.0.3770.90 (Official Build) (64-bit)

Is that in Homestead or on your host machine?

**Comment by andyscraven** [comment]
Yeah on my Macbook

**Comment by staudenmeir** [comment]
I see, I thought you had installed Chrome in Homestead. Dusk can't access Chrome on your host machine.

Install Chromium again: `sudo apt-get install chromium-browser`

Downgrade ChromeDriver to 74: ` php artisan dusk:update 74`

BTW, my updater package is now included in Dusk: ` php artisan dusk:chrome-driver 74`

**Comment by andyscraven** [comment]
BOOM!!!

Thank you so much!

I didn't know it had been integrated.  I will delete the old package

Thanks again!

**Comment by alpharameeztech** [comment]
@staudenmeir I am getting the same error.

I am using chrome version 75.* (the latest)
Laravel 5.8

yet i ams still getting this shitty error

```1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 75
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.15.0-38-generic x86_64)


```
Why do we need to install chrome on Laravel's Homestead. They havent stated that on their documentation.

**Comment by staudenmeir** [comment]
@alpharameeztech What's the result of `chromium-browser --version`?

**Comment by alpharameeztech** [comment]
@staudenmeir 
```
Chromium 70.0.3538.77 Built on Ubuntu , running on Ubuntu 18.04
```
Thank you for response :)

**Comment by petarvasilev91** [comment]
Still happening for me. I get this:

```
There was 1 error:

1) Tests\Browser\CompaniesTest::testCompanies
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-52-generic x86_64)

/var/www/domovakniga.local/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:154
/var/www/domovakniga.local/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:331
/var/www/domovakniga.local/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:144
/var/www/domovakniga.local/tests/DuskTestCase.php:39
/var/www/domovakniga.local/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:192
/var/www/domovakniga.local/vendor/laravel/framework/src/Illuminate/Support/helpers.php:754
/var/www/domovakniga.local/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:193
/var/www/domovakniga.local/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:93
/var/www/domovakniga.local/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:64
/var/www/domovakniga.local/tests/Browser/CompaniesTest.php:42
```
@staudenmeir I tried installing your package and running 'php artisan dusk:update 73' but that didn't help. I also tried 'php artisan dusk:update' and 'php artisan dusk:update 74' no luck there... : (

**Comment by staudenmeir** [comment]
@petarvasilev91 What version of Chrome/Chromium are you using? Are you running Dusk in Homestead?

**Comment by petarvasilev91** [comment]
@staudenmeir you mean as in my general use browser? If so, I am using Chrome 74.0.3729.157. Also, I am not running in Homestead.

**Comment by staudenmeir** [comment]
What error do you get after `php artisan dusk:update 74`?

**Comment by petarvasilev91** [comment]
No error. I get this:

`ChromeDriver binaries successfully updated to version 74.0.3729.6.`

**Comment by staudenmeir** [comment]
When you run Dusk?

**Comment by petarvasilev91** [comment]
I get this on some tests:

```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-52-generic x86_64)
```

**Comment by staudenmeir** [comment]
Dusk is still using the old ChromeDriver. Please try rebooting your machine (if you haven't already).

**Comment by petarvasilev91** [comment]
That solved it! Thanks : )

**Comment by ouily** [comment]
Hello,

`php artisan dusk:chrome-driver 74` doesn't work behind proxy :(

**Comment by staudenmeir** [comment]
@ouily What exactly doesn't work? Is there an error?

**Comment by Snehalyeole** [comment]
I see this error message: 

```Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 44940
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=75.0.3770.100)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'C02WQ11UHV2T', ip: '192.168.2.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: 0   chromedriver                        0x0000000105493319 chromedriver + 3597081
1   chromedriver                        0x0000000105422f73 chromedriver + 3137395```

My Google Chrome is up to date
Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by Snehalyeole** [comment]
My Google Chrome is up to date. Version 75.0.3770.100 (Official Build) (64-bit)
I have latest chrome driver downloaded from here. 
https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.25/

Still I see this error message:

Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=75.0.3770.100)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'C02WQ11UHV2T', ip: '192.168.2.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: 0   chromedriver                        0x0000000105493319 chromedriver + 3597081
1   chromedriver                        0x0000000105422f73 chromedriver + 3137395```

**Comment by staudenmeir** [comment]
@Snehalyeole Is there a specific reason why you are using Selenium? Dusk works without it.

**Comment by JamessBond007** [comment]
I am developing some front end tests.

**Comment by JamessBond007** [comment]
I think I am looking for an answer at wrong place.

**Comment by staudenmeir** [comment]
@ouily The next release will add proxy support: #659

**Comment by fhferreira** [comment]
thank you @staudenmeir i've used successfully the package https://github.com/staudenmeir/dusk-updater

**Comment by ramseyjiang** [comment]
php artisan dusk:update --detect
Chrome version 76.0.3809.87 detected.
No update necessary, your ChromeDriver binary is already on version 76.0.3809.68

When I try to update to 87, it will have errors
php artisan dusk:update 76.0.3809.87

**Comment by ramseyjiang** [comment]
@staudenmeir Yes, It looks don't need to update. But when I run php artisan dusk, it will have errors under below.

Facebook\WebDriver\Exception\SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=76.0.3809.87)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Mac OS X 10.14.5 x86_64)

**Comment by staudenmeir** [comment]
@ramseyjiang If you are using the right ChromeDriver, this must be an issue with Chrome or ChromeDriver.

Can you reproduce the issue on a fresh Laravel installation using the `ExampleTest`?

**Comment by ramseyjiang** [comment]
> @ramseyjiang If you are using the right ChromeDriver, this must be an issue with Chrome or ChromeDriver.
> 
> Can you reproduce the issue on a fresh Laravel installation using the `ExampleTest`?

Sure, I will do it, let you know soon.

**Comment by ramseyjiang** [comment]
Pure laravel, only install dusk, but it still has the error. @staudenmeir 

Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=76.0.3809.87)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Mac OS X 10.14.5 x86_64)

**Comment by staudenmeir** [comment]
I can't reproduce this. We'll have to wait and see if other people report the same issue.

**Comment by ramseyjiang** [comment]
@staudenmeir If you upgrade your chrome to 76.0.3809.87, do you still not see the same issue? I think this issue happened because chrome driver was used in dusk it couldn't upgrade to 76.0.3809.87. I found 76.0.3809.68.zip on the official website, but I cannot find 76.0.3809.87.zip. But my chrome is 76.0.3809.87 version.

**Comment by staudenmeir** [comment]
No, it works for me.

There is no ChromeDriver 76.0.3809.87. Only the first three parts of the version number match: http://chromedriver.chromium.org/downloads/version-selection

**Comment by ramseyjiang** [comment]
@staudenmeir Yes, I know it doesn't have ChromeDriver 76.0.3809.87. But mine still have that issue.

**Comment by l0rb** [comment]
```Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 76
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Linux 4.15.0-46-generic x86_64)```
it says that it needs version 76, but that is clearly what is already installed. is there an issue with minor versions not matching? if yes the error should definitely say what it needs. or some other issue? Also, maybe this issue should be reopened?

**Comment by staudenmeir** [comment]
@l0rb You are using Chrome*Driver* 76 and this version only works with Chrome 76.  You need to update your browser.

**Comment by driesvints** [comment]
I'm going to lock this issue as this has become a dumping ground for support. Please use a support channel if you have further issues with the chrome driver the most common use cases have all been covered in this thread. 

Make sure:

- Your browser version and chrome driver version are the same
- If you still experience a problem, temporarily downgrade to a lower chrome driver and chrome version
